package com.neonto.exportedByUser_s2461812465168012.MyApp;

import android.content.Context;
import android.util.Log;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Locale;

public class LocalizationSheetDataSheet extends DataSheet {

    private HashMap<String, HashMap<String, HashMap<String, Object>>> mKeyMap;
    
    public LocalizationSheetDataSheet(Context context) {
        super(context, "localizationSheet");
        
        loadRowsWithPersistenceName("localizationsheet");
    }
    
    @Override
    public String getName() {
        return "Localization sheet";
    }
    
    @Override
    protected void writeDefaultRowData() {
        ArrayList<HashMap<String, HashMap<String, Object>>> arr = new ArrayList<>();
        HashMap<String, HashMap<String, Object>> row;
        HashMap<String, Object> col;
        
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_tabbar1_button1_585078"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "StopWatch"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_tabbar1_button2_23386"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Timer"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_tabbar1_button3_898979"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "More"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_tabbar1_backbutton_745214"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Alarm"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_tabbar1_backbutton2_819879"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Sleep track"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarm_iconbutton_517158"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_backbutton_819902"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Back"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text_945970"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Alarm Time"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text2_277133"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Alarm Name"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text3_284535"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Select Picture"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text4_248264"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Repeat"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text5_952331"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Ringtone"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text6_477712"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Alarm Color"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text7_234856"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Type"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text8_908425"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Snooze"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text9_667882"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Volume"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text10_335753"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "10:45PM"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text11_735097"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "FF"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text12_921826"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New text. Double-click to edit"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text13_243546"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "RED"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text14_852996"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New text. Double-click to edit"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_iconbutton_932867"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_iconbutton2_575810"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text12_230509"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Mo"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text14_356015"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Tu"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text15_108144"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "We"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text16_1024168"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Th"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text17_596207"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Fr"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text18_495341"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Sa"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text19_618117"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Su"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text20_211398"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Preview Alarm Screen"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_navbarbutton_1002707"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_iconbutton3_469344"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_button_580815"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Go"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_iconbutton3_685821"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New button"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_button2_659709"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New button"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_iconbutton3_988311"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot_1021456"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot2_604636"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot3_671545"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot4_384816"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot5_645750"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot6_636647"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_iconbutton_47221"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_iconbutton2_717925"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot7_381165"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot8_581284"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot7_1048041"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot7_956808"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot7_887758"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot7_412732"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot7_841354"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot7_552966"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot7_150957"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot7_778077"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot7_582692"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot7_646156"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot7_318046"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot7_359508"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot7_877527"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_hotspot7_221332"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil1_text_998937"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Alarm Time"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil1_button_645377"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "OK"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil1_button2_832562"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Cancel"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil2_text_162538"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Alarm Time"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil2_confirmbutton_833964"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "OK"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil2_cancelbutton_715526"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Cancel"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil3_text_664430"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New text. Double-click to edit"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_text21_987325"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "1"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil3_text_371431"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "GG"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil3_text2_38017"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "11:50"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil3_text3_832386"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "AM"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil3_text4_611837"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Mo"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil3_text4_828838"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Tu"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil3_text4_611360"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "We"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil3_text4_731487"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Th"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil3_text4_629373"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Fr"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil3_text4_18834"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Sa"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil3_text4_417146"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Su"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatch_text_831472"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "00:00:00.00"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatch_iconbutton_729062"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatch_button_196356"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Reset"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatch_button2_10087"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Start"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatch_button3_475981"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Lap"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatch_button4_1035560"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Stop"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil4_text_822618"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Lap"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil4_text_992184"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Lap110"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil4_text2_556079"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "00:00:00.00"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil4_text3_201382"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "00:00:00.00"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil4_text_881267"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Lap110"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil4_text2_692563"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "00:00:00.00"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil4_text2_137876"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "00:00:00.00"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_timer_iconbutton_444694"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_timerlistitem_button_120346"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Reset"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_timerlistitem_button2_719994"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Start"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_timerlistitem_button3_392524"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Stop"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_timerlistitem_button4_701033"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "+1"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_timerlistitem_iconbutton_156974"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_timerlistitem_text_932611"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Timer0"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_timerlistitem_text2_589073"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "00:00:00"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil3_vibratebutton_757055"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil3_musicenableicon_1026493"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil3_vibreateenableicon_1006324"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_backbutton_704343"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Setting"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_backbutton2_8861"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Share"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_backbutton3_625712"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Rate Us"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_backbutton4_569828"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Remove ads"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_backbutton5_78912"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Upgrade"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_backbutton6_507584"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Contact Us"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_backbutton7_955348"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "FAQ"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_backbutton8_980058"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "About"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_text_363029"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Setting"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_text2_728139"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Share"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_text3_895533"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Rate Us"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_text4_42769"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Remove ads"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_text5_946278"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Upgrade"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_text6_499994"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Contact Us"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_text7_137219"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "FAQ"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_text8_608591"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "About"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_hotspot_324225"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_hotspot2_12180"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_hotspot2_257405"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_hotspot2_260587"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_hotspot2_654171"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_hotspot2_165767"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_hotspot2_999406"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_hotspot2_811225"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_more_hotspot2_689493"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setting_backbutton_715937"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New button"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setting_text_327992"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "General Settings"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setting_text2_956996"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Alarm Settings"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setting_text3_223855"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "StopWatch / Timer Settings"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setting_hotspot_1042216"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setting_hotspot2_448328"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setting_hotspot3_804749"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_generalsetting_text_218520"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New text. Double-click to edit"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_generalsetting_backbutton_815262"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Back"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_generalsetting_text_291376"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Use 24 hour format"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_generalsetting_text2_158284"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Use phone speaker"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_generalsetting_text3_833644"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Show alarm on lock screen"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_generalsetting_text4_655673"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Show notifications"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_generalsetting_text5_1042671"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Background"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_generalsetting_text6_258256"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Language"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_generalsetting_text7_812651"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Play sound on speakers even when headphones"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_generalsetting_text8_376242"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "When disable your screen will not light up"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_generalsetting_text9_712200"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Alarm, StopWatch, Timer"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_generalsetting_text10_969724"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Choose a background color"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_generalsetting_text11_818058"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "English"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_backbutton_417431"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New button"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_text_773082"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Alarm lock screen image"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_text2_629350"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Snooze alam by"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_text3_919310"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Pressing on screen button"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_text4_178251"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Auto-snooze duration"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_text5_268901"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Never"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_text6_797215"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Max snoozes"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_text7_553961"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Never"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_text8_966594"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Dismiss alarm type"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_text9_271950"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Play in silent mode"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_text10_895938"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Pressing on screen button"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_text11_924100"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Location"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_text12_288912"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Hong Kong"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_screen10_backbutton_345284"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New button"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatchtimersettings_text_873519"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Timer Settings"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatchtimersettings_text2_192589"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Ringtone"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatchtimersettings_text3_753190"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Default"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatchtimersettings_text4_888487"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Vibrate"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatchtimersettings_text5_645711"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Keep screen on"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatchtimersettings_text6_304014"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Keep screen on while running"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatchtimersettings_text7_664485"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Max timer volume"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatchtimersettings_text8_199808"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "1"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatchtimersettings_text9_125031"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "StopWatch Settings"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatchtimersettings_text10_256742"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New text. Double-click to edit"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatchtimersettings_text5_1006415"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Keep screen on"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatchtimersettings_text6_769739"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Keep screen on while running"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_history_text_665583"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "26th May"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_history_button_947733"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "More"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_history_text2_896793"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Timer History"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_history_text3_603352"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Sleep tracking"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordsave_backbutton_559872"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New button"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordsave_text_469493"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Title:"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordsave_backbutton2_188994"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Add a photo"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordsave_text2_928885"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Date:"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordsave_text3_144322"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Time:"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordsave_text4_265829"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Event Type:"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordsave_text5_917431"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Description:"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordsave_button_933231"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Save"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordsave_hotspot_95285"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatchtimersettings_hotspot_853538"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatchtimersettings_hotspot2_347976"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_hotspot_52671"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_hotspot2_560428"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_hotspot3_460086"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_hotspot4_519969"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_hotspot5_398087"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_hotspot6_77755"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_generalsetting_hotspot_842481"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_generalsetting_hotspot2_885480"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_generalsetting_hotspot3_69087"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatchtimersettings_backbutton_341751"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New button"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil3_hotspot_334392"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_navbarbutton_649391"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_backbutton_826909"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New button"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_sounddisableicon_775370"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_vibreatedisableicon_830895"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_musicenableicon_239233"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_vibreateenableicon_777725"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_iconbutton3_421430"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_text12_318732"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Mo"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_text14_660816"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Tu"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_text15_698497"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "We"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_text16_789768"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Th"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_text17_539388"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Fr"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_text18_35307"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Sa"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_text19_899191"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Su"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_text20_288707"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Preview Alarm Screen"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_text_423680"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Alarm Time"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_text2_151363"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Alarm Name"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_text3_11612"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Select Picture"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_text4_186876"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Repeat"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_text5_647516"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Ringtone"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_text6_974560"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Alarm Color"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_text7_993747"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Type"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_text8_943071"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Snooze"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_text9_484524"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Volume"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_timetext_997305"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "10:45PM"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_nametext_963513"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "FF"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_ringtonetext_57185"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "RED"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_volumetext_483214"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "1"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_previewalarmbutton_551453"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_alarmtimebutton_724918"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_alarmnamebutton_8649"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_pickpicturebutton_802309"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_ringtonebutton_346044"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_volumebutton_167140"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_musicbutton_138083"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_vibratebutton_195277"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_satursdaybutton_909410"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_fridaybutton_727982"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_thursdaybutton_577585"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_wednesdaybutton_144943"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_tuesdaybutton_33798"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_mondaybutton_345016"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_sundaybutton_496359"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_yellowbutton_726615"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_blockbutton_767724"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_bluebutton_269759"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_redbutton_63950"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_greenbutton_904573"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_purplebutton_62740"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordsave_text6_662182"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Add a route"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordlistitem_text_491121"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "dd"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordlistitem_text2_797776"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "10:20PM"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordlistitem_text3_649308"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Title:"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordlistitem_text4_886133"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Running"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordlistitem_text5_759437"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Total:"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordlistitem_text6_202406"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Best Time:"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordlistitem_text7_860760"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", " "); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordlistitem_text8_911068"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Description:"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordlistitem_text9_201370"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", " "); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordlistitem_text10_919284"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "11222222s"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordlistitem_text11_784308"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", " "); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_history2_text_1016819"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New text. Double-click to edit"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_history_text_816536"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Sleep tracking"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_history_text2_804371"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "26th May"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_history_hotspot_915534"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_history_text3_242986"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Record Activity"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordlistitem_hotspot_78856"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordlistitem_iconbutton_136023"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordsave_hotspot_423953"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordsave_iconbutton_831539"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_screen13_backbutton_797239"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Back"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recorddetail_text_1013367"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "ICE Skating"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recorddetail_text2_770021"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "06/03/2017"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recorddetail_text3_553321"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Total Time"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recorddetail_text4_387883"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Lap No"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recorddetail_text5_273990"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "10:11"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recorddetail_text6_553960"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "10"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recorddetail_text7_645769"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Best Time"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recorddetail_text8_213808"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Average Time"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recorddetail_text9_1016663"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "00"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recorddetail_text10_52295"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "00"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recorddetail_text11_288536"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "10:00"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_contactus_backbutton_78880"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New button"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_contactus_text_569941"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New text. Double-click to edit"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_contactus_text2_1047847"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Your email address"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_contactus_text_628963"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New text. Double-click to edit"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_contactus_text_834729"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Message"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_contactus_button_1043061"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Send"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_tabbar1_backbutton3_867936"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Back"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_tabbar1_backbutton3_84807"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Back"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_tabbar1_iconbutton_384214"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_tabbar1_backbutton3_994849"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Back"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_history_hotspot_857530"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_history_button_492982"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Sleep"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stopwatch_navbarbutton_661383"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_sleepingdata_backbutton_147067"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New button"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil7_text_1009544"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "10/05/2017"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil7_text2_31039"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Total Sleep"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil7_text3_804066"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Average Sleep"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil7_text4_599857"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Sleep Left"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil7_text5_134500"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Sleep Quality"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil7_text6_609726"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "04:00pm - 05:21am"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil7_iconbutton_668840"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil7_text7_374410"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "10"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil7_text8_182757"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "BAD"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil7_text9_735452"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "5"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil7_text10_524850"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "66"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_stencil7_hotspot_531035"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_recordlist_backbutton_991448"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_button_500125"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Preview alarm screen"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_button_65232"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New button"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_text_249799"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Alarm Time"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_hotspot_268902"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_alarmtimebutton_493002"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_alarmnamebutton_406784"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_pickpicturebutton_891787"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_ringtonebutton_888644"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_editalarm_volumebutton_431206"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_screen17_backbutton_1022970"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "New button"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_setalarm_button_754676"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Preview Alarm"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmscreen_backbutton_303634"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "10%"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmscreen_button_9392"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Dismiss"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_text3_420780"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Alarm alarm by"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_snoozealarmtext_227003"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Pressing on screen button"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmsetting_snoozealarmtypebutton_804645"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmscreen_button2_271395"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "Snooze"); row.put("en", col);
        arr.add(row);
        row = new HashMap<>();
        col = new HashMap<>(); col.put("type", "text"); col.put("value", "neonto_alarmscreen_hotspot_494049"); row.put("key", col);
        col = new HashMap<>(); col.put("type", "text"); col.put("value", ""); row.put("en", col);
        arr.add(row);
        
        mRows = arr;
        
        refreshKeyMap();
    }
    
    public void setRows(ArrayList<HashMap<String, HashMap<String, Object>>> rows) {
        super.setRows(rows);
        
        refreshKeyMap();
    }
    
    public void saveRowWithValues(HashMap<String, Object> values) {
        super.saveRowWithValues(values);
        
        refreshKeyMap();
    }
    
    public void updateRow(int rowIndex, HashMap<String, Object> values) {
        super.updateRow(rowIndex, values);
        
        refreshKeyMap();
    }
    
    public void deleteRow(int rowIndex) {
        super.deleteRow(rowIndex);
        
        refreshKeyMap();
    }
    
    public String getLocalizedStringForKey(String key) {
        Locale locale = mContext.getResources().getConfiguration().locale;
        String str = getLocalizedStringForKey(key, locale.getLanguage());
        return (str != null && str.length() > 0) ? str : getLocalizedStringForKey(key, "en");
    }
    
    public String getLocalizedStringForKey(String key, String locale) {
        HashMap<String, HashMap<String, Object>> rowDesc = mKeyMap.get(key);
        if (rowDesc == null || !rowDesc.containsKey(locale)) {
            return null;
        }
        return (String) rowDesc.get(locale).get("value");
    }
    
    private void refreshKeyMap() {
        mKeyMap = new HashMap<>();
        
        for (HashMap<String, HashMap<String, Object>> row : mRows) {
            HashMap<String, Object> keyDesc = row.get("key");
            String key = (String) keyDesc.get("value");
            mKeyMap.put(key, row);
        }
    }

}
