/*
 * This package name is autogenerated by Neonto Studio
 * when using 'Open in Android Studio'.
 * 
 * To change the package name, use 'Export' instead.
 */

package com.neonto.exportedByUser_s2461812465168012.MyApp;

import android.app.Fragment;
import android.app.FragmentManager;
import android.app.FragmentTransaction;
import android.os.Bundle;
import android.support.v13.app.FragmentPagerAdapter;
import android.support.v4.view.ViewPager;
import android.support.v7.app.ActionBar;
import android.support.v7.app.ActionBarActivity;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;

import com.neonto.exportedByUser_s2461812465168012.MyApp.R;

public class TabBar1Fragment extends Fragment {

    /**
     * The {@link android.support.v4.view.PagerAdapter} that will provide
     * fragments for each of the sections. We use a
     * {@link FragmentPagerAdapter} derivative, which will keep every
     * loaded fragment in memory. If this becomes too memory intensive, it
     * may be best to switch to a
     * {@link android.support.v13.app.FragmentStatePagerAdapter}.
     */
    TabBar1FragmentPagerAdapter mPagerAdapter;

    /**
     * The {@link ViewPager} that will host the section contents.
     */
    ViewPager mViewPager;

    public TabBar1Fragment() {  // fragment must have a constructor
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        final View rootView = inflater.inflate(R.layout.fragment_tab_bar1, container, false);
        
        final ActionBar actionBar = ((ActionBarActivity) getActivity()).getSupportActionBar();
        actionBar.setNavigationMode(ActionBar.NAVIGATION_MODE_TABS);
        actionBar.setDisplayShowHomeEnabled(false);
        actionBar.setDisplayShowTitleEnabled(false);

        mPagerAdapter = new TabBar1FragmentPagerAdapter(getFragmentManager());

        mViewPager = (ViewPager) rootView.findViewById(R.id.tab_bar1_viewpager);
        mViewPager.setAdapter(mPagerAdapter);

        mViewPager.setOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageSelected(int i) {
                actionBar.setSelectedNavigationItem(i);
                switch (i) {
                    case 0: getActivity().setTitle("Sleeping"); break;
                    case 1: getActivity().setTitle("Alarm"); break;
                    case 2: getActivity().setTitle("StopWatch"); break;
                    case 3: getActivity().setTitle("Timer"); break;
                    case 4: getActivity().setTitle("More"); break;
                }

            }

            @Override
            public void onPageScrolled(int i, float v, int i2) {
            }

            @Override
            public void onPageScrollStateChanged(int i) {
            }
        });
        
        ActionBar.Tab tab;
        
        tab = actionBar.newTab()
                .setText(AppData.getLocalizedString("neonto_tabbar1_backbutton2_819879", ""))
                .setIcon(R.drawable.tab_bar1_fragment_tab_icon0)
                .setTabListener(new TabListener(mViewPager));
        actionBar.addTab(tab);
        
        tab = actionBar.newTab()
                .setText(AppData.getLocalizedString("neonto_tabbar1_backbutton_745214", ""))
                .setIcon(R.drawable.tab_bar1_fragment_tab_icon1)
                .setTabListener(new TabListener(mViewPager));
        actionBar.addTab(tab);
        
        tab = actionBar.newTab()
                .setText(AppData.getLocalizedString("neonto_tabbar1_button1_585078", ""))
                .setIcon(R.drawable.tab_bar1_fragment_tab_icon2)
                .setTabListener(new TabListener(mViewPager));
        actionBar.addTab(tab);
        
        tab = actionBar.newTab()
                .setText(AppData.getLocalizedString("neonto_tabbar1_button2_23386", ""))
                .setIcon(R.drawable.tab_bar1_fragment_tab_icon3)
                .setTabListener(new TabListener(mViewPager));
        actionBar.addTab(tab);
        
        tab = actionBar.newTab()
                .setText(AppData.getLocalizedString("neonto_tabbar1_button3_898979", ""))
                .setIcon(R.drawable.tab_bar1_fragment_tab_icon4)
                .setTabListener(new TabListener(mViewPager));
        actionBar.addTab(tab);
        
        
        try {
            String action = getActivity().getIntent().getAction();
            java.util.Set<String> categories = getActivity().getIntent().getCategories();
            if (action == android.content.Intent.ACTION_MAIN && categories != null && categories.contains(android.content.Intent.CATEGORY_LAUNCHER)) {
                // Default page when the app starts.
                mViewPager.setCurrentItem(0);
            } else {
                Bundle bundle = getActivity().getIntent().getExtras();
                final int tabIndex = bundle.getInt("tabIndex");
                mViewPager.setCurrentItem(tabIndex);
            }
        } catch (Exception e) {}

        return rootView;
    }

    /**
     * A {@link FragmentPagerAdapter} that returns a fragment corresponding to
     * one of the sections/tabs/pages.
     */
    public class TabBar1FragmentPagerAdapter extends FragmentPagerAdapter {

        public TabBar1FragmentPagerAdapter(FragmentManager fm) {
            super(fm);
        }

        @Override
        public Fragment getItem(int position) {
                        
            switch (position) {
            case 0:
                return new SleepingFragment();
            case 1:
                return new AlarmFragment();
            case 2:
                return new StopWatchFragment();
            case 3:
                return new TimerFragment();
            case 4:
                return new MoreFragment();
            }
            return null;

        }

        @Override
        public int getCount() {
            return 5;
        }

        @Override
        public CharSequence getPageTitle(int position) {
            return "";
        }
    }
    
    public static class TabListener implements ActionBar.TabListener {
        private ViewPager mViewPager;
        
        public TabListener(ViewPager viewPager) {
            mViewPager = viewPager;
        }
        
        public void onTabSelected(ActionBar.Tab tab, android.support.v4.app.FragmentTransaction ft) {
            mViewPager.setCurrentItem(tab.getPosition());
        }
        
        public void onTabUnselected(ActionBar.Tab tab, android.support.v4.app.FragmentTransaction ft) {
        }
        
        public void onTabReselected(ActionBar.Tab tab, android.support.v4.app.FragmentTransaction ft) {
        }
    }

}
